### PR TITLE
[wifi-login-pages] Used terser-plugin to reduce js file size #167

### LINKED ISSUE #167: [wifi-login-pages] Reduce webpack build size
[Tree shaking (here's a guide)](https://webpack.js.org/guides/tree-shaking/) may help us to reduce build size to less than 250 KB.

Any other legitimate technique can be used as well.

### PR DESCRIPTION
**Pull request by frappelatte28**
Reduces build size from 269kb to 267kb

Related to #167

### CODE REVIEW

**Comment by frappelatte28** [comment]
Hey @nemesisdesign @niteshsinha17 will you please share your reviews on it?

**Review by nemesisdesign — COMMENTED** [review]
Sorry I'm under heavy load and it will take me some time before I'm able to test this. Please do not get discouraged and keep finding ways to reduce the build size, I'll test each PR asap.

**Comment by frappelatte28** [comment]
Thanks for replying back @nemesisdesign, I will just see what other options are there for reducing build size!

**Review by nemesisdesign — APPROVED** [review]
Thanks @frappelatte28 :+1:

**Comment by frappelatte28** [comment]
My pleasure @nemesisdesign :-)

**Pull request merged**
