### PR TITLE
[feature] Added support for django-sesame links #478

### LINKED ISSUE #478: [feature] Support django-sesame links
Needed for https://github.com/openwisp/openwisp-radius/pull/355.

### PR DESCRIPTION
**Pull request by codesankalp**
Closes #478

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
I tried fixing a conflict and I must have screwed up something!

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
See https://github.com/openwisp/openwisp-radius/pull/355#pullrequestreview-846725908

**Comment by codesankalp** [comment]
https://github.com/openwisp/openwisp-radius/pull/355#issuecomment-1008544019

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Thanks @codesankalp, you're right, with the right configuration it works.

There's one failing test here, do you know why?

**Comment by codesankalp** [comment]
> There's one failing test here, do you know why?

Because this branch is using openwisp-radius master branch.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@codesankalp @pandafy https://github.com/openwisp/openwisp-radius/pull/355 is merged but there's a test here that keeps failing, can you fix it please?
PS: I updated the secret for the openwisp-radius cache in the CI build, the test fails also locally in my env (`<Login /> interactions › should authenticate if sesame link is in url`, this is the test that fails).

**Comment by codesankalp** [comment]
> @codesankalp @pandafy [openwisp/openwisp-radius#355](https://github.com/openwisp/openwisp-radius/pull/355) is merged but there's a test here that keeps failing, can you fix it please? PS: I updated the secret for the openwisp-radius cache in the CI build, the test fails also locally in my env (`<Login /> interactions › should authenticate if sesame link is in url`, this is the test that fails).

I will check and fix this.

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
