### PR TITLE
[change] Added warning icon for errors #358

### LINKED ISSUE #358: [change] Add an icon to replace ! in errors
Errors in forms now show an exlamation mark, but we could add a warning icon which would be better.

It would be better to address https://github.com/openwisp/openwisp-wifi-login-pages/issues/357 before this.

### PR DESCRIPTION
**Pull request by codesankalp**
Used the warning icon and removed exclamation sign.

Closes #358

### CODE REVIEW

**Comment by codesankalp** [comment]
image

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Can yo please try the other icon? I mean the one which would show as filled white and the exlamation mark would be transparent (and hence red), let me know if not clear.

**Comment by codesankalp** [comment]
image

**Comment by codesankalp** [comment]
image

I didn't made the icon size smaller because the exclamation mark was not visible properly.

**Review by nemesisdesign — APPROVED** [review]
Thanks

**Pull request merged**
