### PR TITLE
[feature] Logout without breaking auto login #171

### LINKED ISSUE #171: [wifi-login-pages] Logout without breaking auto-login
To be done after #63.

When a user logs out, once they go back to the log in page, they will not be auto logged in if they enabled the remember me checkbox.

We need to find a way to make the auto-login feature work when the remember-me checkbox is enabled, so that when they connect to the WiFi again, they'll be automatically logged in when they open the page.

Right now users get automatically logged in only if they did not click the logout button.

The problem is that right now if one clicks logout, they're taken back to the login page, and without clearing the cookie session, they would be immediately logged in again.

So we could implement something like the following:

- if the remember me checkbox is enabled and the user logs out, ask them (with a modal message) if they want to be automatically logged in the next time they open the wifi
- if they choose no, the behavior is unchanged
- if they choose yes, the cookie/session data is not erased, but the captive portal log out is performed normally
- once the log out is performed, instead of taking back the user to the log in page, we direct them at a new page or a screen in the same status page, which communicates the successful log out and shows a button that says "Log in again" or something similar, which links the log in page

### PR DESCRIPTION
**Pull request by codesankalp**
Logout action is performed without removing cookies and sessions

when auto login is set for the next time.

Closes #171

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
I pushed some improvements, please check che code changes, test them and verify all is ok, let me know if there's any issue.

**Comment by codesankalp** [comment]
> I pushed some improvements, please check che code changes, test them and verify all is ok, let me know if there's any issue.

Yes, tested them and the style looks much better than the previous one.
It is working fine.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Thanks @codesankalp, while testing I found a corner case to handle:

- log in
- then log out (clicking on yes)
- now stop the development server of openwisp-radius
- click log in again

There's an error (rightly so) and we're taken back to the same page, can you make sure that if an error happens while logging in again the user, we redirect to the login page?

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
I got mixed results during testing.

### Going to login page again does not auto log in

Try this:

- log in
- log out, click yes in the modal
- now go back to sign in without clicking on "log me in again"

Following this path the user does not get logged back in again.
Why is that?

Please read the issue (#171) description again:

> When a user logs out, once they go back to the log in page, they will not be auto logged in if they enabled the remember me checkbox.
> 
> We need to find a way to make the auto-login feature work when the remember-me checkbox is enabled, so that when they connect to the WiFi again, they'll be automatically logged in when they open the page.

The current implementation does not meet the goal: when the user is presented the captive page again, they will not be automatically logged in. They do only if they click on that button ("log me in again"), but it's pointless, because users will close the page.

All this work we are doing is to allow users to log in automatically without having to insert username and password each time, **is the goal clear**?

### Testing with a captive portal is giving me different results

Adding the captive portal into the mix gives me totally and different and incorrect results.
In the next days I will work on adding a couple debug views in opewnsip-radius which we can use in this app.
I will try to replicate the same issues and report here.

**Update**: during testing, this condition is not triggered because of these lines:

https://github.com/openwisp/openwisp-wifi-login-pages/blob/9133c58eaef774cde9e41c0b4c299f0dffe77a16/client/components/status/status.js#L185-L186

If you temporarily disable that if, and let the code inside the if run, you will be able to replicate the same behavior I see.

**Comment by codesankalp** [comment]
> Thanks @codesankalp, while testing I found a corner case to handle:
> 
> * log in
> * then log out (clicking on yes)
> * now stop the development server of openwisp-radius
> * click log in again
> 
> There's an error (rightly so) and we're taken back to the same page, can you make sure that if an error happens while logging in again the user, we redirect to the login page?

I fixed this.
Will push the commit soon.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
I think the lazy loading is causing issues during captive portal logout but it's hard to replicate unless you set up a captive portal.

Here's my understanding of what is happening:

- log out happens, access to the network is shut down for some instants by the firewall
- even though the firewall should allow access to the domain where our app is hosted, for a few seconds this doesn't happen
- this causes the download of the JS chunk which has the code for "logged out successfully" to fail downloading
- therefore the page stays blocked loading, sometimes it finally shows up after 10-20 seconds, sometimes seems to not show at all

I tried eliminating Lazy loading for Logout and seems to work.

The issue happens also if I click on "no" to "do you want to login again...", because going back to log in triggers the download of the chunk which contains `Login` so I think we have to give up lazy loading for both `Login` and `Logout` components.

So I suggest to proceed as follows:

- rebase this PR on the latest master and fix conflicts
- disable lazy loading for `Logout`
- find out if there's anything you can do to shrink the size of logout further
- disable also lazy loading for Login component but in a separate commit

With these changes we should be done, I will do some final testing to confirm.

**Comment by codesankalp** [comment]
> find out if there's anything you can do to shrink the size of logout further

It's of 267 B now.

**Review by nemesisdesign — COMMENTED** [review]
Looks good! I will give it another round of testing asap.

**Review by nemesisdesign — APPROVED** [review]

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
