### PR TITLE
Added webpack bundle analyser to the codebase 

### PR DESCRIPTION
**Pull request by frappelatte28**
solves #191

### CODE REVIEW

**Comment by frappelatte28** [comment]
@nemesisdesign  please kindly review this pr

**Review by nemesisdesign — APPROVED** [review]
Sorry for my late review @frappelatte28.

Tested and it's good. I did a minor improvement to the README https://github.com/openwisp/openwisp-wifi-login-pages/pull/196/commits/9bf71c8cc7b53c59d3ffaa76ddf46ef98c31da86.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@frappelatte28 the build is now failing for a style issue, could you fix it please?

You can also squash my changes within your commits, no need to keep the commits for the merge branch and for the README improvement as separate commits.

**Comment by frappelatte28** [comment]
I fixed the issue, please review it @nemesisdesign.

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
