### PR TITLE
[change] Updated X logo #743

### LINKED ISSUE #743: [change] Outdated Twitter Logo
The website currently displays an outdated version of the Twitter logo. The logo being used is not in sync with the latest branding guidelines.

Steps to Reproduce:

Visit the website
Navigate to the section displaying social media links.
Observe the Twitter logo and compare it with the latest Twitter branding guidelines.
Expected Result:
The Twitter logo should adhere to the most recent branding guidelines provided by Twitter.

Actual Result:
The current Twitter logo appears to be outdated and may not align with the latest branding standards.

https://github.com/openwisp/openwisp-wifi-login-pages/assets/120818337/56128ad6-d5ff-4847-bef6-5ab2f5b57e8e

### PR DESCRIPTION
**Pull request by d1vyanshu-kumar**
The traditional blue bird symbol, once synonymous with Twitter, has been updated to a minimalist black-and-white “X” which is currently the official one. Fixes #743
 
Screenshot 2024-02-10 at 9 52 27 PM

### CODE REVIEW

**Review by nemesifier — CHANGES_REQUESTED** [review]
@d1vyanshu-kumar looks good! The build is failing because the test snapshots are not up to date (google jest test snapshots to find out more), see the build failure output which indicates the command to run to update the snapshots:

```
Snapshot Summary
 › 5 snapshots failed from 1 test suite. Inspect your code changes or run `yarn run coverage -u` to update them.
```

**Comment by d1vyanshu-kumar** [comment]
@nemesifier, please check it now.

Screenshot 2024-02-12 at 5 48 20 PM

**Review by nemesifier — CHANGES_REQUESTED** [review]
@d1vyanshu-kumar please always use commits that pass the commit message check test, as per our guidelines, always run `./run-qa-checks` before pushing.

**Comment by d1vyanshu-kumar** [comment]
@nemesifier things looks good now?

**Review by nemesifier — APPROVED** [review]

**Comment by nemesifier** [comment]
Thanks :+1:

**Pull request merged**
