### PR TITLE
[deps] Update history #125

### LINKED ISSUE #125: [deps] Update history as suggested by dependabot but fix issues
This dependabot change is failing because of a mock that seems cannot be done in that way anymore: https://github.com/openwisp/openwisp-wifi-login-pages/pull/117.
There should be another recommended way of accomplishing the same thing, we should find it and replace those lines that cause the build failure.

### PR DESCRIPTION
**Pull request by garvitchittora**
Closes #125 

After updating dependency packages in yarn.lock file. Now all tests are passed.

@Purhan @nemesisdesign please review this PR.

Screenshot from 2021-03-20 23-11-30

### CODE REVIEW

**Review by Purhan — CHANGES_REQUESTED** [review]
@garvitchittora please don't use formatters. This is very difficult to review with the amount of unrelated changes.

Push the commit with only the lines you have changed

**Comment by Purhan** [comment]
Also the current build failed because of the commit message, consider using something like the following:
```
[deps] Update history #125

Closes #125
```

**Comment by codesankalp** [comment]
@garvitchittora You may need to follow the commit guidelines of OpenWISP to pass the QA-checks.
Instead of changing the title, you need to change the commit message and force-push again your changes with the correct commit message as mentioned by @Purhan 
You can also try running `./openwisp-qa-checks` for passing checks locally.

**Review by nemesisdesign — APPROVED** [review]
Thanks for updating the yarn.lock

**Pull request merged**
