### PR TITLE
[wifi-login-pages] Set page titles #155

### LINKED ISSUE #155: [wifi-login-pages] Set page title
For each page of the app we should have a title, eg: `{page_title} - {organization_name}`.

We should have a `title` attribute in the org-config of each component, translatable, eg:
```yaml
registration_form:
    title:
        en: "Sign up"
```

We should add a test for each component to ensure the tile is changed as expected.

Also the main title should be allowed to be multilingual, now we have:

```yaml
client:
  # <title> value
  title: "WiFi Login"
```

we shall switch to:
```yaml
client:
  # <title> value
  title:
    en: "WiFi Login"
    it: "Accesso WiFi"
    # other languages...
```

### PR DESCRIPTION
**Pull request by sankha555**
Added page (component) titles for default components. Page titles and
help-texts have been added in English and Francais languages.

Fixes #155

### CODE REVIEW

**Comment by sankha555** [comment]
@nemesisdesign I have made a PR to add titles to the components in the default org-configuration file. I have added the page titles in English. I also knew intermediate French from my school days and so with a bit of that and googling helped to add the page titles and help texts in French too. Kindly take a look and suggest any required changes. Thanks!

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@sankha555 this PR does not solve #155, I didn't ask to add translations, I asked to implement something that is now missing. Please read again the issue description and if it's not clear ask questions before jumping to coding.

**Comment by sankha555** [comment]
I see now, I'll have to add the test for the title change. Also, I'll remove the translations in the component headings. Just one clarification, I'll also have to add the title tags to each of the js file of the component and not just org-config, right? I mistook it to be only in the org-config before. Please do let me know in case I am still missing out on something. Thanks!

**Comment by nemesisdesign** [comment]
I'm closing for now. Feel free to reopen if you resume.

**Pull request closed without merging**
