### PR TITLE
 [change] Reduced size of main chunk #321

### LINKED ISSUE #321: [change] Reduce size of main chunk
I think there's room to further reduce the size of the main chunk of JS generated by webpack.

We'll have to explore possible solutions to do this.

We could also add a step to the build which generates files compressed with gzip and brotli, so that the webserver can be configured to use these instead of compressing on the fly, which saves CPU on the server.

### LINKED ISSUE #341: [change] Load modal content when requested
https://github.com/openwisp/openwisp-wifi-login-pages/pull/332#pullrequestreview-724762506

1. Load privacy policy and t&c modal content by making an API request when user wants it to load.
2. Support for different languages content should be supported.

### PR DESCRIPTION
**Pull request by codesankalp**
Closes #321
Closes #341

### CODE REVIEW

**Comment by codesankalp** [comment]
image

I am working on increasing test coverage.

**Review by nemesisdesign — COMMENTED** [review]
https://github.com/openwisp/openwisp-wifi-login-pages/pull/303 is merged! You can rebase now :blush:.

BTW: have you already any idea of a way to preload the status component in login and the logout component in status without having these included in the main chunk? Is it possible to preload just these components without having them included in any chunk?

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Great progress @codesankalp!

I see the gzip files are generated as:

`1.chunk.[contenthash].gz`

Shouldn't [contenthash] be an actual hash?
BTW shouldn't also the non gzipped files contain an hash so that whenever we change the application the browser automatically loads the new version without having to ask the user to refresh the cache?

Also, why did you separate the login chunk from the main chunk?
This may work better on HTTP2, but I would like to know if you did it on purpose and why.

Could you try compress some static assets as well? For example, I see the SVG files are quite big, maybe we can optimize/compress those a bit.
I did a quick test with some tools found online and I can get up to 20% of saving but I wonder if something better can be achieved with some other tool?
I don't think compression here is so important because these will be gzipped by nginx, but finding some optimization tool which can reduce the size of the XML without loosing much quality could be a win. 

I will test this on a staging system next week to find out if these changes cause any issue when used with a captive portal.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
What about TOS and privacy policy, can we ensure these are loaded only when requested and not preloaded?

Right now when I click on one of the two I don't see any HTTP request, therefore I think it's being preloaded. Same for sign up page.

In prod the privacy policy and TOS will be quite long, more over they will be different for every language so we have to be careful to ensure these are loaded only when requested.

**Comment by codesankalp** [comment]
> Also, why did you separate the login chunk from the main chunk?
> This may work better on HTTP2, but I would like to know if you did it on purpose and why.

While implementing the auto-login feature, you said that due to lazy loading it is not working as expected in deployment. So I thought to separate it from the main chunk to load it faster (as it was earlier implemented).

**Comment by codesankalp** [comment]
> I did a quick test with some tools found online and I can get up to 20% of saving but I wonder if something better can be achieved with some other tool?

I tried to use [image-minimizer-webpack-plugin](https://webpack.js.org/plugins/image-minimizer-webpack-plugin/) but it is not working as expected and many other dependencies to work correctly. So I compressed all the files manually.

**Comment by codesankalp** [comment]
@nemesisdesign Should I separate #341 Commit from this PR?

**Comment by nemesisdesign** [comment]
@codesankalp if it was a completely separate bugfix yes, but it's still related to reducing the size of the main chunk so it's ok to have it here, it makes the job of verifying whether all the changes in this branch reach the goal easier. Thanks!

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
I have been testing the gzip_static module of nginx and I have found some unexpected issues plus some areas for improvement.

## Premise

I generated the files I discuss below with:

```
NODE_ENV=production yarn build --production
```

### .gz suffix not added in a way that is recognized by nginx gzip_static 

The gzip_static module of nginx looks if there's a file with the same name but with the additional `.gz` suffix, so if a file is named `hello.js` nginx/gzip_static looks for `hello.js.gz`, but I see files like `15.5ae6383bafb23fc57159.chunk.gz`, which isn't working (it should be `15.5ae6383bafb23fc57159.chunk.js.gz`, the same applies for brotli.

### SVG files

Svg files are not being compressed, but the gzip_static module of nginx can look for these and use them, right now these are being compressed on the fly by nginx, Is it possible to compress also svg during build process so we avoid nginx to do this unnecessary extra work?

### Compressed version of some JS files is not being created

Here's the output of `ls -1 dist` with some additional comments, I removed some files which aren't relevant (eg: fonts).

> 0.a98a2933244409b998bb.chunk.js

:point_up_2: No compressed version of this file.

> 13.771218bd7ff6e9533dd3.chunk.gz
> 13.771218bd7ff6e9533dd3.chunk.js
> 13.771218bd7ff6e9533dd3.chunk.js.br
> 14.ad22ad61bee0196ec96b.chunk.gz
> 14.ad22ad61bee0196ec96b.chunk.js
> 14.ad22ad61bee0196ec96b.chunk.js.br
> 15.5ae6383bafb23fc57159.chunk.gz
> 15.5ae6383bafb23fc57159.chunk.js
> 15.5ae6383bafb23fc57159.chunk.js.br
> 16.43674d7afb31a8f9a6e4.chunk.gz
> 16.43674d7afb31a8f9a6e4.chunk.js
> 16.43674d7afb31a8f9a6e4.chunk.js.br
> 17.1b294d600c8284a5fa41.chunk.gz
> 17.1b294d600c8284a5fa41.chunk.js
> 17.1b294d600c8284a5fa41.chunk.js.br
> 18.3a23bb59bb8165cc99d0.chunk.gz
> 18.3a23bb59bb8165cc99d0.chunk.js
> 18.3a23bb59bb8165cc99d0.chunk.js.br
> 19.2118d9b68acf98d4004f.chunk.js

:point_up_2: No compressed version of this file.

> 1.9e12f0c1a8769142ee5d.chunk.gz
> 1.9e12f0c1a8769142ee5d.chunk.js
> 1.9e12f0c1a8769142ee5d.chunk.js.br
> 20.90ea2891035c2110ff9e.chunk.js

:point_up_2: No compressed version of this file.

> 20a11dee9e4f7d988f9575bc86510dbd.svg

Note: svg are not compressed as mentioned above, would be good to gzip them as well because these are XML files.

> 21.39ad11b762db211dd586.chunk.js
> 22.905dc5722b53feedbb51.chunk.js
> 23.a99092ed8619dd31f3ff.chunk.js
> 24.dd9a05afe425aea3f0b6.chunk.js
> 25.5d150812d6d7694c4d7c.chunk.js
> 26.ee9f256082075ffda757.chunk.js
> 27.d5908a91b9035bd58483.chunk.js

No compressed version of all these files above (from 21 to 27).

> 28.fec39e112e84838d8150.chunk.gz
> 28.fec39e112e84838d8150.chunk.js
> 28.fec39e112e84838d8150.chunk.js.br
> 29.1d16de1a534662b53548.chunk.js

:point_up_2: No compressed version of this file.

> 2.ebb883336272a6751b7d.chunk.gz
> 2.ebb883336272a6751b7d.chunk.js
> 2.ebb883336272a6751b7d.chunk.js.br
> 30.12e1ce34a7d068824fec.chunk.js
> 31.d40fdc2f62c15a62dc24.chunk.js
> 32.3d44eec33f208b797c81.chunk.js
> 33.a52019e306059e0a90c2.chunk.js
> 34.cbb335aaed9a9c492206.chunk.js

No compressed version of all these files above (from 30 to 34).

> 35.65fb202459d002a043ef.chunk.gz
> 35.65fb202459d002a043ef.chunk.js
> 35.65fb202459d002a043ef.chunk.js.br
> 36.7728420a69ea23811988.chunk.js

:point_up_2: No compressed version of this file.

> 3.babdd27cc039f8a064e4.chunk.gz
> 3.babdd27cc039f8a064e4.chunk.js
> 3.babdd27cc039f8a064e4.chunk.js.br
> 4.a38b8edef1dbc51604fa.chunk.gz
> 4.a38b8edef1dbc51604fa.chunk.js
> 4.a38b8edef1dbc51604fa.chunk.js.br
> 4.a38b8edef1dbc51604fa.chunk.js.LICENSE
> 4.a38b8edef1dbc51604fa.chunk.js.LICENSE.txt
> 4.a38b8edef1dbc51604fa.chunk.js.map
> 5.f82fc93185d63ca705bc.chunk.js

:point_up_2: No compressed version of this file.

> 6.1c97386673dfd769d0c7.chunk.js

:point_up_2: No compressed version of this file.

> 75d572bd95912abf48b25b0da57078db.svg
> Login.3570c3a356b9243ea938.chunk.gz
> Login.3570c3a356b9243ea938.chunk.js
> Login.3570c3a356b9243ea938.chunk.js.br
> Logout.ff73369933ce54ee4111.chunk.js

:point_up_2: No compressed version of this file.

> main.7ca120ae176fd8437ed9.chunk.gz
> main.7ca120ae176fd8437ed9.chunk.js
> main.7ca120ae176fd8437ed9.chunk.js.br
> runtime.76c58b95832e9be6cbc0.js

:point_up_2: No compressed version of this file.

> Status.fd427c2672c4a20e7789.chunk.gz
> Status.fd427c2672c4a20e7789.chunk.js
> Status.fd427c2672c4a20e7789.chunk.js.br
> vendors~main.97e82d4caeaf0a62b48d.chunk.gz
> vendors~main.97e82d4caeaf0a62b48d.chunk.js
> vendors~main.97e82d4caeaf0a62b48d.chunk.js.br
> vendors~main.97e82d4caeaf0a62b48d.chunk.js.LICENSE
> vendors~main.97e82d4caeaf0a62b48d.chunk.js.LICENSE.txt
> vendors~main.97e82d4caeaf0a62b48d.chunk.js.map

### Static assets of organizations not compressed nor hashed

The following command:

```
ls -1 dist/assets/default/
```

shows:

```
facebook.svg
favicon.png
google.svg
index.css
linkedin.svg
openwisp-logo-black.svg
openwisp-logo-white.svg
twitter.svg
```

Can you achieve compression of these files as well?

It would be amazing if we could include a hash in the filename and ensure the hashed version is used, at least for the CSS, because this can change often, not sure it can be done for the images nor if it really makes sense, but if it can be done with little effort it would be good to have it because once every now and then images can be changed too.

**Comment by codesankalp** [comment]
> .gz suffix not added in a way that is recognized by nginx gzip_static

Fixed by using name and base in compression plugin.


> SVG files

Added compression of SVG files in both compression and brotli webpack plugin.



> Compressed version of some JS files is not being created

Actually, I have separated the chunk for the CSS file but the compression plugin makes it in one file that's why it is not different for each file. Also, there are many files generating so I reverted it back to avoid complexity. Now `gz` file is present for each file.


> Static assets of organizations not compressed nor hashed

I have added the support for compression by removing the threshold and adding SVG to the compression plugin but I faced a problem in hashing i.e. these files can be hashed using `path.resolve(CURRENT_WORKING_DIR, "dist/assets", "[path][name].[contenthash].[ext]")` but while running the server these assets are not loaded because config file do not contain the name with hash for these assets so the `getAssetPath` returns the prev path which is 404. So I avoid hashing here.

**Comment by codesankalp** [comment]
> index.html CSS not being minimized

Solved using MiniCssExtractPlugin and OptimizeCssAssetsPlugin

**Review by nemesisdesign — COMMENTED** [review]
@codesankalp is this warning something we have to worry about?

```
WARNING in chunk 2 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ../node_modules/css-loader/dist/cjs.js!../node_modules/react-toastify/dist/ReactToastify.css
despite it was not able to fulfill desired ordering with these modules:
 * css ../node_modules/css-loader/dist/cjs.js!../node_modules/react-phone-input-2/lib/style.css
   - couldn't fulfill desired order of chunk group(s) Login
   - while fulfilling desired order of chunk group(s) ,
```

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
Can you rebase on the latest master and fix conflicts please?

**Comment by codesankalp** [comment]
> @codesankalp is this warning something we have to worry about?
> 
> ```
> WARNING in chunk 2 [mini-css-extract-plugin]
> Conflicting order. Following module has been added:
>  * css ../node_modules/css-loader/dist/cjs.js!../node_modules/react-toastify/dist/ReactToastify.css
> despite it was not able to fulfill desired ordering with these modules:
>  * css ../node_modules/css-loader/dist/cjs.js!../node_modules/react-phone-input-2/lib/style.css
>    - couldn't fulfill desired order of chunk group(s) Login
>    - while fulfilling desired order of chunk group(s) ,
> ```

It's not a problem, I removed this warning in the latest commit.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
In this last round of testing I found this file which is not gzipped:

openat(AT_FDCWD, "/opt/openwisp2/wifi-login-pages/dist/2.9c7cd0a3bae46631cf48.chunk.js.gz", O_RDONLY|O_NONBLOCK) = -1 ENOENT (No such file or directory)

I see that the brotli compressed file is present but not gzip, can you please fix this?

We should be done with this!

**Comment by codesankalp** [comment]
> In this last round of testing I found this file which is not gzipped:
> 
> ```
> openat(AT_FDCWD, "/opt/openwisp2/wifi-login-pages/dist/2.9c7cd0a3bae46631cf48.chunk.js.gz", O_RDONLY|O_NONBLOCK) = -1 ENOENT (No such file or directory)
> ```
> 
> I see that the brotli compressed file is present but not gzip, can you please fix this?
> 
> We should be done with this!

min ratio is greater than 0.7, That's why it is not compressing. Fixed this in the latest commit.

**Review by nemesisdesign — APPROVED** [review]
Great work, thanks! :+1:

**Pull request merged**
