### PR TITLE
 Improve Twitter logo.

### LINKED ISSUE #743: [change] Outdated Twitter Logo
The website currently displays an outdated version of the Twitter logo. The logo being used is not in sync with the latest branding guidelines.

Steps to Reproduce:

Visit the website
Navigate to the section displaying social media links.
Observe the Twitter logo and compare it with the latest Twitter branding guidelines.
Expected Result:
The Twitter logo should adhere to the most recent branding guidelines provided by Twitter.

Actual Result:
The current Twitter logo appears to be outdated and may not align with the latest branding standards.

https://github.com/openwisp/openwisp-wifi-login-pages/assets/120818337/56128ad6-d5ff-4847-bef6-5ab2f5b57e8e

### PR DESCRIPTION
**Pull request by d1vyanshu-kumar**
Closes #743 
After Modification:
Screenshot 2024-01-24 at 9 34 20 PM

### CODE REVIEW

**Review by nemesifier — CHANGES_REQUESTED** [review]
I think we should change also the text "Login with Twitter" to "Login with X".

The commit message does not follow our [commit message conventions](https://openwisp.io/docs/developer/contributing.html#commit-message-style-guidelines),
please change it to "[change] Updated X logo".
We shouldn't use "[fix]" here because this is not a bug fix.

**Comment by pandafy** [comment]
I don't see this blue X logo on https://about.twitter.com/en/who-we-are/brand-toolkit. Where did you download this from @d1vyanshu-kumar ?

**Comment by d1vyanshu-kumar** [comment]
I found this logo from this website:
https://tishonator.com/blog/upgrading-to-the-latest-twitter-logo-on-your-website
The logo is blue because of the fill="#1da1f2" attribute in the <path> element. This sets the colour of the logo to the official Twitter blue.

here u can see the final  code:

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" version="1.1">
  <path fill="#1da1f2" d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
</svg>

**Comment by pandafy** [comment]
> @pandafy I found this logo from this website: https://tishonator.com/blog/upgrading-to-the-latest-twitter-logo-on-your-website The logo is blue because of the fill="#1da1f2" attribute in the element. This sets the colour of the logo to the official Twitter blue.

@d1vyanshu-kumar I think you will need to tweak CSS which is changing the colour of the logo. The new logo is black and white.

**Comment by d1vyanshu-kumar** [comment]
Screenshot 2024-02-02 at 7 46 09 PM

–> I have changed the logo and the text from “login with Twitter” to “login with X”. Please review it and give me your feedback.

**Comment by pandafy** [comment]
@d1vyanshu-kumar the QA checks and tests are failing. Can you fix them?

**Pull request closed without merging**
