### PR TITLE
[change] Improved change password component to include old pwd field #366

### LINKED ISSUE #366: [change] Improve change password component to include old password field
Depends on https://github.com/openwisp/openwisp-radius/issues/289.

### PR DESCRIPTION
**Pull request by codesankalp**
Added support for the current password field.

Closes #366

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
I restarted the CI build but it keeps failing, can you look into it when you have time please?

**Comment by codesankalp** [comment]
> I restarted the CI build but it keeps failing, can you look into it when you have time, please?

It depends on https://github.com/openwisp/openwisp-radius/pull/296. It will pass after it's merged in the master branch @nemesisdesign.

**Review by nemesisdesign — COMMENTED** [review]
@codesankalp https://github.com/openwisp/openwisp-radius/pull/296 is merged but it keeps on failing, is it due to a cache issue or what else? Can you please look into it and fix it?

**Comment by codesankalp** [comment]
> @codesankalp [openwisp/openwisp-radius#296](https://github.com/openwisp/openwisp-radius/pull/296) is merged but it keeps on failing, is it due to a cache issue or what else? Can you please look into it and fix it?

It's due to cache. As the setup.py was not changed the key remains the same. I have added a commit to forcefully change the cache version from GitHub secrets.

**Review by nemesisdesign — APPROVED** [review]
Thanks :+1:

**Pull request merged**
