### PR TITLE
[bug] Fixed unique key props error when no links #169

### LINKED ISSUE #169: [bug] Fix unique key props error when no links
Whenever there is no link present in the footer unique key props error is shown in the browser console.

### PR DESCRIPTION
**Pull request by codesankalp**
Added check for undefined link url

Closes #169

### CODE REVIEW

**Comment by codesankalp** [comment]
@nemesisdesign Needs your review.

**Review by nemesisdesign — COMMENTED** [review]
I have one doubt: how to replicate the issue in the first place?

I tried setting:

```
    footer:
      links: []
```

In the config but I don't get any error. I don't understand why this change is necessary.
There's no point having a link which doesn't have `url` set, or does it and if yes why? I lost track of this issue.

**Comment by codesankalp** [comment]
@nemesisdesign in the config generator i.e.
https://github.com/openwisp/openwisp-wifi-login-pages/blob/3934656624fd465939433dfd22b242529775525f/internals/generators/organization/config.yml.hbs#L88-L90
when creating a new org new config file is being generated with empty links i.e. the URL is not present in the generated config file which gives a unique key props error as URL is not present.
So, Instead of using `index` as a key, I checked whether a URL is present in the link, if it's present it will be a unique key and if it's not present then simply it will return null. And it works for other cases also (because without a URL there is no need for `<a>` tag.).

In the comment of @niteshsinha17 [here](https://github.com/openwisp/openwisp-wifi-login-pages/pull/181#issuecomment-805086283), he suggested using `links: [ ]` but if I will use this then it will be hard to get the text for the link.

**Comment by niteshsinha17** [comment]
>he suggested using links: [ ] but if I will use this then it will be hard to get the text for the link.

@codesankalp Can you please explain why do we need a text without any link in the footer links section?

**Comment by codesankalp** [comment]
> > he suggested using links: [ ] but if I will use this then it will be hard to get the text for the link.
> 
> @codesankalp Can you please explain why do we need a text without any link in the footer links section?

@niteshsinha17 The text is not required without any link but suppose if there will be a link present then it is hard to get the text from `links: [ ]`. Also in the `config.yml.hbs` file the footer is present with field text without any link URL.

**Comment by niteshsinha17** [comment]
> > > he suggested using links: [ ] but if I will use this then it will be hard to get the text for the link.
> > 
> > 
> > @codesankalp Can you please explain why do we need a text without any link in the footer links section?
> 
> @niteshsinha17 The text is not required without any link but suppose if there will be a link present then it is hard to get the text from `links: [ ]`. Also in the `config.yml.hbs` file the footer is present with field text without any link URL.

I think you are right

**Comment by codesankalp** [comment]
> @codesankalp I think it's not an issue only if new links are added manually. It is better than checking of url of all the links even if it have a valid url. What do you think?

I can't get this point. Can you explain to me the format you are suggesting by taking an example of a link?

**Comment by niteshsinha17** [comment]
@codesankalp Lets wrap this now.
> Also in the config.yml.hbs file the footer is present with field text without any link URL.

I don't know what was the intention of doing this. But t don't thing there any point of having a link in the footer without a link.

>I can't get this point. Can you explain to me the format you are suggesting by taking an example of a link?

Its not so confusion part.  You know we can edit config file of an org any time. We are just having empty array initially to avoid that warning that also means having no link initially. We can change it when we want to add links in the footer for any org.

**Review by nemesisdesign — COMMENTED** [review]
ok, good, I think we should do the smae for header, can you proceed please?

**Review by nemesisdesign — APPROVED** [review]

**Pull request merged**
