### PR TITLE
[CSS] restyle components

### PR DESCRIPTION
**Pull request by Vivekrajput20**

### CODE REVIEW

**Comment by Vivekrajput20** [comment]
@nemesisdesign  I have updated the PR with all the changes.

**Comment by Vivekrajput20** [comment]
@nemesisdesign I've added both the logos to the default assets and the font colour has been changed to black.

**Comment by Vivekrajput20** [comment]
@nemesisdesign  please review it.

**Comment by nemesisdesign** [comment]
Hey @Vivekrajput20, sorry for the delay, I sent you some messages via IM on gitter.

**Pull request merged**
