### PR TITLE
[CI] Move CI to github actions #153

### LINKED ISSUE #153: [CI] Move CI to github actions
Move CI to github actions.

### PR DESCRIPTION
**Pull request by sankha555**
Added a YAML file (```.github/workflow/build.yml```) to specify steps to be performed in build using Github Actions. 

Fixes #153

### CODE REVIEW

**Comment by sankha555** [comment]
@nemesisdesign I have made a minimal boilerplate for the build file to be used by Github Actions. Could you please take a look and suggest what all changes and additions are required? I'll proceed accordingly then. Thanks!

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@sankha555 please ensure to test it in your fork and send me the link to the build once it's successful or let me know if you encounter roadblocks.

**Review by nemesisdesign — COMMENTED** [review]
I gave a quick look to the code here and it doesn't do much, you have to port what's being done in travis to github actions, please look at other similar PRs in other repos that are being done or have been done recently.

**Comment by sankha555** [comment]
Sure, I'll do the required things then and let you know about my progress. Thanks!

**Comment by nemesisdesign** [comment]
I'm closing for now. Feel free to reopen if you resume.

**Pull request closed without merging**
