### PR TITLE
[ci] Replace set-output with GITHUB_OUTPUT in CI workflow

### LINKED ISSUE #669: [ci] Replace set-output in CI build
[QA-Checks](https://github.com/openwisp/openwisp-wifi-login-pages/actions/runs/5402871155/jobs/9818724288#step:3:5)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by Shiva953**
Fixes #669 
This PR updates the CI workflow to replace the deprecated `set-output` commands with the new `GITHUB_OUTPUT` aligning with the latest changes in GitHub Actions.

### CODE REVIEW

**Review by nemesifier — COMMENTED** [review]
Thanks @Shiva953, it looks good! Can you please provide a link to documentation regarding guidance migrating from the v2 to the v3 so we can double check?

**Comment by Shiva953** [comment]
> Thanks @Shiva953, it looks good! Can you please provide a link to documentation regarding guidance migrating from the v2 to the v3 so we can double check?

These might be helpful
https://blog.eidinger.info/why-and-how-to-adopt-actionscheckoutv3-in-your-github-action-workflow
https://action-slack.netlify.app/migration/01-migrate-from-v2-to-v3/

**Comment by Shiva953** [comment]
@nemesifier any updates?

**Review by nemesifier — COMMENTED** [review]
Sorry I lost this one from my radar, it should be good, what do you think @pandafy?
If you could rebase this on the latest master it would be helpful.

**Review by pandafy — COMMENTED** [review]
@Shiva953 there's even v4 released now which used Node 20 as run-time. 

https://github.com/actions/checkout/releases

Also, your linked pages were not very helpful. While mentioning any changes to underlying software, always provide references from the author (here GitHub) instead of articles. 

E.g. I found this GitHub Blog for deprecation of  `set-output-name`. 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Shiva953** [comment]
> @Shiva953 there's even v4 released now which used Node 20 as run-time.
> 
> https://github.com/actions/checkout/releases
> 
> Also, your linked pages were not very helpful. While mentioning any changes to underlying software, always provide references from the author (here GitHub) instead of articles.
> 
> E.g. I found this GitHub Blog for deprecation of `set-output-name`. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

got it, should I update it to v4 now?

**Comment by Shiva953** [comment]
@pandafy any updates on this?

**Comment by nemesifier** [comment]
> Also, your linked pages were not very helpful. While mentioning any changes to underlying software, always provide references from the author (here GitHub) instead of articles.

If you can that would be useful, so you can go ahead and update.

**Review by nemesifier — APPROVED** [review]

**Comment by nemesifier** [comment]
Thanks @Shiva953 :+1:

**Pull request merged**
